sudo: false
dist: trusty
language: node_js
node_js:
- '6'
install: travis_retry gem install s3_website -v 3.1.0
before_script: "./build.sh"
script: "./deploy/s3_deploy.sh"
env:
  global:
  - secure: YlMermtsbqihre+8Bhb+N+pZh3/twTUSLzi8EFEK7UyHtg4u4rPZxnH06AtXdvct47zZgQEKEubTdUQxixhZDNF8bhJFajqfEXhF9f65S9KZMsboMlIkZWactwQ19bb/RCgshCOZtbKOf6qT2sWM96tlRvWDeOX0G6SvTmIZWcY=
  - secure: ft/ynFwLiZn7/bQj1uRMpV0w/gcJ/S2Rj3qBG8tMEsQ/FmEi2IuaVPgfv14DlDWLjmXrnOkFeuTjzfCt44XB5sWkdi2nWYtW1IJLNsa7ETjJQLJqWlU4zSTfBaizoyrwaDe64NnJLc0ypfIsXknC7ri6wSdr4f9TyNfdaFtDT4o=
