s3_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['S3_SECRET_KEY'] %>
s3_bucket: models-resources
s3_endpoint: us-east-1
cloudfront_distribution_id: E1QHTGVGYD1DWZ
s3_key_prefix: jsmol

<% if ENV['TRAVIS_BRANCH'] == 'production' %>
# in this case we are going to deploy this branch to the top level of the domain
# so we need to ignore the version and branch folders
ignore_on_server: ^jsmol/(version/|branch/)
<% else %>
# in this case we are going to deploy this code to a subfolder of either the branch
# or version folder. So ignore everything except this folder.
ignore_on_server: ^(?!jsmol/<%= Regexp.escape(ENV['DEPLOY_DIR']) %>/)
<% end %>
max_age:
  "jsmol/*": 600 # 10 minutes
  "jsmol/version/*": 31536000 # 1 year
  "jsmol/branch/*": 0

gzip:
  - .html
  - .css
  - .js
  - .txt
  - .md
  # specific for JSmol:
  - .spt
  - .pdb
  - .mol
  - .mdl
  - .smol
  - .sd
  - .sdf
  - .xyz
  - .jxyz
  - .jvxl
  - .pse
  - .map
  - .magres
  - .jdx
  - .molden
  - .xodydata
